# Generated by Django 4.0.3 on 2022-05-10 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('courseName', models.CharField(max_length=20)),
                ('courseInstructor', models.CharField(max_length=50)),
                ('meetingTime', models.TimeField()),
                ('sectionNum', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('userType', models.CharField(choices=[('Admin', 'Admin'), ('Instructor', 'Instructor'), ('TA', 'Ta')], default='TA', max_length=10)),
                ('email', models.CharField(max_length=40)),
                ('first_name', models.CharField(max_length=20)),
                ('last_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('labNum', models.IntegerField()),
                ('labTA', models.CharField(max_length=50)),
                ('courseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling.course')),
                ('userID', models.ManyToManyField(to='TA_Scheduling.myuser')),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='userID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='TA_Scheduling.myuser'),
        ),
    ]
